//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IGarcOn")]
public interface IGarcOn
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarcOn/GetCategoriesAndProducts", ReplyAction="http://tempuri.org/IGarcOn/GetCategoriesAndProductsResponse")]
    string GetCategoriesAndProducts();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarcOn/AddCategory", ReplyAction="http://tempuri.org/IGarcOn/AddCategoryResponse")]
    void AddCategory(int tipo, string descricao);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarcOn/AddProduct", ReplyAction="http://tempuri.org/IGarcOn/AddProductResponse")]
    void AddProduct(long idCategoria, string nome, string descricao, double valor);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGarcOnChannel : IGarcOn, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GarcOnClient : System.ServiceModel.ClientBase<IGarcOn>, IGarcOn
{
    
    public GarcOnClient()
    {
    }
    
    public GarcOnClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GarcOnClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GarcOnClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GarcOnClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetCategoriesAndProducts()
    {
        return base.Channel.GetCategoriesAndProducts();
    }
    
    public void AddCategory(int tipo, string descricao)
    {
        base.Channel.AddCategory(tipo, descricao);
    }
    
    public void AddProduct(long idCategoria, string nome, string descricao, double valor)
    {
        base.Channel.AddProduct(idCategoria, nome, descricao, valor);
    }
}
